DROP TABLE NEW_SCHEMA.PATIENT
;
DROP TABLE NEW_SCHEMA.TEST
;
DROP TABLE NEW_SCHEMA.DOCTOR
;
CREATE TABLE NEW_SCHEMA.PATIENT(
SS NUMERIC(10) NOT NULL,
DOCTORDSS NUMERIC(10) NOT NULL,
NAME VARCHAR(255),
INSURANCE VARCHAR(255),
DATE_ADMITTED DATE,
DATE_CHECKED_OUT DATE,
PRIMARY KEY (SS, DOCTORDSS),
FOREIGN KEY (DOCTORDSS) REFERENCES DOCTOR (DSS)
);

CREATE TABLE NEW_SCHEMA.TEST(
ID NUMERIC(10),
DOCTORDSS NUMERIC(10),
PATIENTDSS NUMERIC(10),
NAME VARCHAR(255),
TESTDATE DATE,
TESTTIME timestamp,
RESULT VARCHAR(255),
PRIMARY KEY (ID),
FOREIGN KEY (PATIENTDSS) REFERENCES PATIENT(SS),
FOREIGN KEY (DOCTORDSS) REFERENCES DOCTOR(DSS)
);

CREATE TABLE NEW_SCHEMA.DOCTOR(
DSS NUMERIC(10),
NAME VARCHAR(255),
SPECIALIZATION VARCHAR(255),
PRIMARY KEY (DSS)
)
;
--  First insert data into DOCTOR then PATIENT then TEST

INSERT INTO NEW_SCHEMA.DOCTOR(
DSS,
NAME,
SPECIALIZATION
)
VALUES
(123,'Doctor 1', 'Neurologist'),
(124,'Doctor 2', 'Opthalmologist')
;

select * from NEW_SCHEMA.DOCTOR
;

INSERT INTO NEW_SCHEMA.PATIENT(
SS,
DOCTORDSS,
NAME,
INSURANCE,
DATE_ADMITTED,
DATE_CHECKED_OUT
)
VALUES
(100, 123, 'Patient 1', 'BAJAJ Alliance', STR_TO_DATE('04-14-2025','%m-%d-%Y'), STR_TO_DATE('04-18-2025', '%m-%d-%Y'))
;

INSERT INTO NEW_SCHEMA.TEST(
ID,
DOCTORDSS,
PATIENTDSS,
NAME,
TESTDATE,
TESTTIME,
RESULT
)
VALUES
(524, 123, 100, 'CT-SCAN', STR_TO_DATE('04-14-2025','%m-%d-%Y'), STR_TO_DATE('04-14-2025 20:32:12','%m-%d-%Y %H:%i:%s'), 'POSITIVE')
;

INSERT INTO NEW_SCHEMA.TEST(
ID,
DOCTORDSS,
PATIENTDSS,
NAME,
TESTDATE,
TESTTIME
)
SELECT 555, DOCTORDSS, SS, 'X-ray', DATE_ADMITTED, null
from new_schema.patient
;

select * from NEW_SCHEMA.TEST
;

select * from NEW_SCHEMA.PATIENT
;

select D.NAME
FROM NEW_SCHEMA.PATIENT as P
JOIN NEW_SCHEMA.DOCTOR as D
ON P.DOCTORDSS = D.DSS
WHERE P.SS = 100 -- patient id
;

select * from NEW_SCHEMA.PATIENT;
select * from NEW_SCHEMA.DOCTOR;
select * from NEW_SCHEMA.TEST;

select 'constant1';
select 123;


UPDATE new_schema.TEST
SET RESULT = 'NEGATIVE'
WHERE RESULT is null
;
